kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  storageClassName: wcp-storage-general
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
      