apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: metadata-store-db
    kapp.k14s.io/app: "1694575251688377524"
    kapp.k14s.io/association: v1.6a56581d895cf07f7c8fd0c43fe6f89f
  name: postgres-db-pv-claim
  namespace: metadata-store
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
