apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: faas1
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-medium-cpu
      storageClass: wcp-storage-general
    workers:
      count: 2
      class: best-effort-medium-cpu
      storageClass: wcp-storage-general
  distribution:
    fullVersion: 1.20.7+vmware.1-tkg.1.7fb9067
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["172.10.0.0/16"]
      pods:
        cidrBlocks: ["172.20.0.0/16"]
