apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: syd-tmc-1
spec:
  settings:
    network:
      services:
        cidrBlocks:
        - 172.30.0.0/16
      pods:
        cidrBlocks:
        - 172.31.0.0/16
      serviceDomain: cluster.local
    storage:
      defaultClass: k8s-general-storage
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-large
      storageClass: k8s-general-storage
      tkr:
        reference:
          name: v1.24.11---vmware.1-fips.1-tkg.1
    nodePools:
    - name: default-nodepool
      replicas: 3
      vmClass: best-effort-large
      storageClass: k8s-general-storage
