
AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lVTU8vK09HZzN1d2hLcWhyUC8wN2Rlb3RmdExZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pERWlNQ0FHQTFVRUF3d1pZMjl1ZEhKdmJHeGxjakV1ZEdGdWVuVXVjR3hoZVhCbGJqQWVGdzB5TXpBMApNVGt3TWpReU1qWmFGdzB5TkRBME1UZ3dNalF5TWpaYU1DUXhJakFnQmdOVkJBTU1HV052Ym5SeWIyeHNaWEl4CkxuUmhibnAxTG5Cc1lYbHdaVzR3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGgKeVNUSzhQRU10S05Ld1lDbWtYRkhqYnpYU2lTaTJ0RXhRNm5UWHl3Yno4OWpuVUlyVHY2YVRCK3piUjVoK1pCSQovN0d5Y0pPVnB2Q2xNQ0tNMmJWTWM1YWtEZFFYZFE3UTcvTktXdUR4UjhseVQ1TlVwRHcrSFhBaDl6bmJYejY2CnRxdElxR0hUemdMK21hMXh6Wi94bUVrSDlNVjNETnlzVWtzbjhGSXhUYnd1YVJJRHhuSUp0V2lvT2xUczhpekUKRy9tSzVhQVZrd2UvTW93cXA1Rk8zaHRGalNFYmp6cnNFWFlhWDBlRFNBQnd5REM2UXBPZXZmWjdQUmIyN2g1OApGRXZXZWRjQndTeTNiaXZPNEpyUUtQSWVWN28vMU9aNFQyU1NGbmlrbE5sekcyZnF2MEl6ZGNvM0Q0c05Ub28xCi8wN0dvL1UwQW1sZjlQRXZsSW56QWdNQkFBR2pMakFzTUNvR0ExVWRFUVFqTUNHSEJBcGFrQlNDR1dOdmJuUnkKYjJ4c1pYSXhMblJoYm5wMUxuQnNZWGx3Wlc0d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLWk8wWTg4RHd1ZApFZG9vQkVodlZ0WTI0Tk5Ga2lqU1dPcjQzRG1VTmkxNWc5a2V4Z1FEb2hkVmMxaDZBWEhyUHNVSFFEdWtaOVd3Cmp0aCtGdVhzOXpqcDVyV0RCZFdKakdpcTlJOEw3aStPclVsMW1iK29XUUZOZ1FqL0ZZK0ZMRTkxSnBzZG9WNUkKUlFOOElhR2pIS3pyUFJSc0t2aVB4TzB0WHV5V1F6V3VxQWt4aVBNN1JKQVNTV3Rha0RkVEFySkxUNDI1MXB4MwpxdGw4OENyRkl4c0t0MmFjSUVzdWIxc2hVblJOZzFLYUlVOVJESmxnb1dQRTJGd3hsRVJBWU5vTk1iTVJUdFJmCjhRWlZrQjZzWWlzZDFEc256Vk9oZnRGdXFGc3NKWmtIbUs5S1dLY05pK0pEM1VjaE5EbS9zYmR2dG52L0pTUVUKa2J3cjRyZUNEQW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
AVI_CLOUD_NAME: Default-Cloud
AVI_CONTROL_PLANE_HA_PROVIDER: "false"
AVI_CONTROL_PLANE_NETWORK: pg-lab-vip-146
AVI_CONTROL_PLANE_NETWORK_CIDR: 10.90.146.0/25
AVI_CONTROLLER: 10.90.144.20
AVI_DATA_NETWORK: pg-lab-vip-146
AVI_DATA_NETWORK_CIDR: 10.90.146.0/25
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_MANAGEMENT_CLUSTER_CONTROL_PLANE_VIP_NETWORK_CIDR: 10.90.146.0/25
AVI_MANAGEMENT_CLUSTER_CONTROL_PLANE_VIP_NETWORK_NAME: pg-lab-vip-146
AVI_MANAGEMENT_CLUSTER_SERVICE_ENGINE_GROUP: Default-Group
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: 10.90.146.0/25
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: pg-lab-vip-146
AVI_PASSWORD: <encoded:RzBsZGZpJGg=>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_ANNOTATIONS: description:apj-tanzu-test-lab,location:Lab
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_LABELS: class:test,country:india
CLUSTER_NAME: lab-manager-1
CLUSTER_PLAN: prod
CONTROL_PLANE_MACHINE_COUNT: 3
WORKER_MACHINE_COUNT: 3
ENABLE_AUDIT_LOGGING: "false"
ENABLE_CEIP_PARTICIPATION: "true"
ENABLE_MHC: "true"
ENABLE_MHC_CONTROL_PLANE: "true"
ENABLE_MHC_WORKER_NODE: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
MHC_MAX_UNHEALTHY_CONTROL_PLANE: 60%
MHC_MAX_UNHEALTHY_WORKER_NODE: 60%
MHC_UNKNOWN_STATUS_TIMEOUT: 20m
MHC_FALSE_STATUS_TIMEOUT: 40m
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: ubuntu
OS_VERSION: "20.04"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_ENDPOINT: 10.90.144.16
VSPHERE_CONTROL_PLANE_MEM_MIB: "16384"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "4"
VSPHERE_DATACENTER: /Lab
VSPHERE_DATASTORE: /Lab/datastore/vsanDatastore
VSPHERE_FOLDER: /Lab/vm/tkg
VSPHERE_INSECURE: "true"
VSPHERE_NETWORK: /Lab/network/pg-lab-mgmt-144
VSPHERE_PASSWORD: <encoded:RzBsZGZpJGg=>
VSPHERE_RESOURCE_POOL: /Lab/host/Cluster1/Resources/tkg
VSPHERE_SERVER: 10.90.144.10
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCw+bKF5H9+GIfmRd8OL4Lh+e07wYGiumwp4Qu2xSuqNWsDlF3Q6Mc6D5gtCDqlE1rIyeUJHoivQFO1WBd3q1fUvTA56i41K4QB8MycYG1Nz3i1nbRmo6+5VSvYebPtCXw9lu2e2tCsEJFo/fB1Y9p4J990UIq7oQINTSU/SnMTl8FKcUCarsMTLOkPRtsbQJPdf+sn8GHmnIcFj0F47UHLMFpJvvh6ZpyXOMGuwV+P4LSU8C7QsnRJXDdVMntoSY9MDWp4L48dYMBJseZ2JXi1y4l5HPkHUdSVAOg21G4FlhJTJt5tDx4pxovVHYJdr5dTYE1gk8VVU9tLwv7xElkkOziiAULEcm1gMETwGY/5QRpN461vW/2D5EpdYgd3ke0kT5xUdGyPFzK5vu7UKLX9L32ZBtSCfPhzkF38aP2XWtlgUh7dOEBkY/5T5XnqwfHW9EAIb1nif31PNW+hHH1OEL01D9IJHfWl8ygfYKriFxZmsTs0gzxcXepozuYTIopJMl75WrYOnva/vERBNVNOS9CcPFNXJc+TdLwMYaz6EXtFMaNRhy1m3Sdik0IwhBoiCVEHz+QhDHOxqgmYf3CCdNG/0dhaZDFVvsSYclYQzXIT4U7LMerHezzuPMqULHi+rAmuHU4WRubOIkWxJFiwpuHdtDtD+be89FA2LxP/FQ== tanzu@home.local
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: tkgmgr@tanzu.playpen
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "16384"
VSPHERE_WORKER_NUM_CPUS: "4"
WORKER_ROLLOUT_STRATEGY: ""
