apiVersion: v1
items:
- apiVersion: gcm.vmware.com/v1alpha1
  kind: ManagedCluster
  metadata:
    annotations:
      defaultPSPCreated: "true"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gcm.vmware.com/v1alpha1","kind":"ManagedCluster","metadata":{"annotations":{},"name":"cluster-prod-1","namespace":"production"},"spec":{"distribution":{"version":"v1.15.0+vmware.1.20-guest.1.14"},"settings":{"imageName":"photon-ova","network":{"cni":{"name":"calico"},"nameservers":["192.168.200.17","192.168.200.16"],"pods":{"cidrBlocks":["192.0.2.0/16"]},"serviceDomain":"syddsc.local","services":{"cidrBlocks":["198.51.100.0/12"]}}},"storage":{"classes":["spinning-disk","ssd"]},"topology":{"masters":{"class":"guaranteed-small","count":1,"storageClass":"wcp-gold-storage-policy"},"workers":{"class":"guaranteed-small","count":2,"storageClass":"wcp-gold-storage-policy"}}}}
    creationTimestamp: "2019-10-24T23:56:59Z"
    finalizers:
    - managedcluster.gcm.vmware.com
    - foregroundDeletion
    generation: 2
    name: cluster-prod-1
    namespace: production
    resourceVersion: "3131490"
    selfLink: /apis/gcm.vmware.com/v1alpha1/namespaces/production/managedclusters/cluster-prod-1
    uid: 2c2f51cf-886d-4155-b42a-a0731840fc0a
  spec:
    distribution:
      version: v1.15.0+vmware.1.20-guest.1.14
    settings:
      imageName: photon-ova
      network:
        cni:
          name: calico
        nameservers:
        - 192.168.200.17
        - 192.168.200.16
        pods:
          cidrBlocks:
          - 192.0.2.0/16
        serviceDomain: syddsc.local
        services:
          cidrBlocks:
          - 198.51.100.0/12
      storage: {}
    topology:
      masters:
        class: guaranteed-small
        count: 1
        storageClass: wcp-gold-storage-policy
      workers:
        class: guaranteed-small
        count: 2
        storageClass: wcp-gold-storage-policy
  status:
    cloudprovider:
      name: vmware-guest-cluster
    clusterApiStatus:
      apiEndpoints:
      - host: 10.244.1.82
        port: 6443
      providerStatus:
        kubeconfigSecretRef:
          kind: Secret
          name: cluster-prod-1-kubeconfig
          namespace: production
        metadata:
          creationTimestamp: null
    cni:
      name: calico
    version: v1.15.0+vmware.1.20-guest.1.14
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
