apiVersion: sources.tanzu.vmware.com/v1alpha1
kind: VSphereSource
metadata:
  name: source
spec:
  address: https://vcenter.home.local
  skipTLSVerify: true
  secretRef:
    name: vsphere-credentials
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  checkpointConfig:
    maxAgeSeconds: 300
    periodSeconds: 10
  #payloadEncoding: application/json
