kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: tkg-storage-default
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  svStorageClass: "vSAN Default Storage Policy"
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

