kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wcp-storage-db
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  svStorageClass: wcp-storage-general
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

