apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: web-c-1
  labels:
    app: web-c-1
    web: demo
spec:
  className: best-effort-small
  imageName: centos-stream-8-vmservice-v1alpha1-1638306496810
  powerState: poweredOn
  storageClass: shared-general
  networkInterfaces:
  - networkName: dportgroup-vm-41
    networkType: vsphere-distributed
  vmMetadata:
    configMapName: web-c-1
    transport: OvfEnv
  volumes:
    - name: c1-disk-1
      persistentVolumeClaim:
        claimName: c1-disk-1
