apiVersion: cpi.tanzu.vmware.com/v1alpha1
kind: VSphereCPIConfig
metadata:
  name: edge-shared-1
  namespace: default
spec:
  vsphereCPI:
    mode: vsphereCPI
    tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    vmNetwork:
      excludeExternalSubnetCidr: 10.90.145.30/32
      excludeInternalSubnetCidr: 10.90.145.30/32
---
apiVersion: cpi.tanzu.vmware.com/v1alpha1
kind: KubevipCPIConfig
metadata:
  name: edge-shared-1
  namespace: default
spec:
  loadbalancerIPRanges: 10.90.145.31-10.90.145.39
---
apiVersion: run.tanzu.vmware.com/v1alpha3
kind: ClusterBootstrap
metadata:
  annotations:
    tkg.tanzu.vmware.com/add-missing-fields-from-tkr: v1.25.7---vmware.2-tkg.1
  name: edge-shared-1
  namespace: default
spec:
  additionalPackages:
  - refName: metrics-server*
  - refName: secretgen-controller*
  - refName: pinniped*
  - refName: kube-vip-cloud-provider*
    valuesFrom:
      providerRef:
        apiGroup: cpi.tanzu.vmware.com
        kind: KubevipCPIConfig
        name: edge-shared-1
  cpi:
    refName: vsphere-cpi*
    valuesFrom:
      providerRef:
        apiGroup: cpi.tanzu.vmware.com
        kind: VSphereCPIConfig
        name: edge-shared-1
  kapp:
    refName: kapp-controller*
---
apiVersion: v1
kind: Secret
metadata:
  name: edge-shared-1
  namespace: default
stringData:
  password: G0ldfi$h
  username: tkgmgr@tanzu.playpen
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    osInfo: photon,3,amd64
    tkg.tanzu.vmware.com/cluster-controlplane-endpoint: 10.90.145.30
    tkg/plan: dev
  labels:
    tkg.tanzu.vmware.com/cluster-name: edge-shared-1
  name: edge-shared-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.96.0.0/11
    services:
      cidrBlocks:
      - 100.64.0.0/13
  topology:
    class: tkg-vsphere-default-v1.0.0
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
      replicas: 1
    variables:
    - name: cni
      value: antrea
    - name: controlPlaneCertificateRotation
      value:
        activate: true
        daysBefore: 90
    - name: auditLogging
      value:
        enabled: false
    - name: podSecurityStandard
      value:
        audit: baseline
        deactivated: false
        warn: baseline
    - name: apiServerEndpoint
      value: 10.90.145.30
    - name: aviAPIServerHAProvider
      value: false
    - name: vcenter
      value:
        cloneMode: fullClone
        datacenter: /Edge
        datastore: /Edge/datastore/edgelocal1
        folder: /Edge/vm/tkg
        network: /Edge/network/pg-edge-mgmt-145
        resourcePool: /Edge/host/EdgeCluster1/Resources/tkg_shared
        server: 10.90.144.10
        storagePolicyID: ""
        template: /Edge/vm/templates/photon-3-kube-v1.25.7+vmware.2
        tlsThumbprint: ""
    - name: user
      value:
        sshAuthorizedKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCw+bKF5H9+GIfmRd8OL4Lh+e07wYGiumwp4Qu2xSuqNWsDlF3Q6Mc6D5gtCDqlE1rIyeUJHoivQFO1WBd3q1fUvTA56i41K4QB8MycYG1Nz3i1nbRmo6+5VSvYebPtCXw9lu2e2tCsEJFo/fB1Y9p4J990UIq7oQINTSU/SnMTl8FKcUCarsMTLOkPRtsbQJPdf+sn8GHmnIcFj0F47UHLMFpJvvh6ZpyXOMGuwV+P4LSU8C7QsnRJXDdVMntoSY9MDWp4L48dYMBJseZ2JXi1y4l5HPkHUdSVAOg21G4FlhJTJt5tDx4pxovVHYJdr5dTYE1gk8VVU9tLwv7xElkkOziiAULEcm1gMETwGY/5QRpN461vW/2D5EpdYgd3ke0kT5xUdGyPFzK5vu7UKLX9L32ZBtSCfPhzkF38aP2XWtlgUh7dOEBkY/5T5XnqwfHW9EAIb1nif31PNW+hHH1OEL01D9IJHfWl8ygfYKriFxZmsTs0gzxcXepozuYTIopJMl75WrYOnva/vERBNVNOS9CcPFNXJc+TdLwMYaz6EXtFMaNRhy1m3Sdik0IwhBoiCVEHz+QhDHOxqgmYf3CCdNG/0dhaZDFVvsSYclYQzXIT4U7LMerHezzuPMqULHi+rAmuHU4WRubOIkWxJFiwpuHdtDtD+be89FA2LxP/FQ==
    - name: controlPlane
      value:
        machine:
          diskGiB: 40
          memoryMiB: 8192
          numCPUs: 2
    - name: worker
      value:
        count: 2
        machine:
          diskGiB: 40
          memoryMiB: 8192
          numCPUs: 2
    - name: kubeVipLoadBalancerProvider
      value: true
    version: v1.25.7+vmware.2-tkg.1
    workers:
      machineDeployments:
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-0
        replicas: 2
