apiVersion: cpi.tanzu.vmware.com/v1alpha1
kind: VSphereCPIConfig
metadata:
  name: edge-tiny-1
  namespace: default
spec:
  vsphereCPI:
    mode: vsphereCPI
    tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    vmNetwork:
      excludeExternalSubnetCidr: 10.90.145.20/32
      excludeInternalSubnetCidr: 10.90.145.20/32
---
apiVersion: v1
kind: Secret
metadata:
  name: edge-tiny-1
  namespace: default
stringData:
  password: G0ldfi$h
  username: tkgmgr@tanzu.playpen
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    tkg.tanzu.vmware.com/cluster-controlplane-endpoint: 10.90.145.20
    run.tanzu.vmware.com/resolve-tkr: 'tkr.tanzu.vmware.com/tiny'
  labels:
    tkg.tanzu.vmware.com/cluster-name: edge-tiny-1
  name: edge-tiny-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.96.0.0/11
    services:
      cidrBlocks:
      - 100.64.0.0/13
  topology:
    class: tkg-vsphere-default-v1.0.0
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
      replicas: 1
    variables:
    - name: cni
      value: antrea
    - name: controlPlaneCertificateRotation
      value:
        activate: true
        daysBefore: 90
    - name: controlPlaneTaint
      value: false  
    - name: imageRepository
      value:
        host: projects.registry.vmware.com/tkg
    - name: auditLogging
      value:
        enabled: false
    - name: trust
      value:
        additionalTrustedCAs:
        - data: LS0tL[...]0tLQo=
          name: imageRepository
    - name: apiServerEndpoint
      value: 10.90.145.20
    - name: aviAPIServerHAProvider
      value: false
    - name: vcenter
      value:
        cloneMode: fullClone
        datacenter: /Edge
        datastore: /Edge/datastore/edgelocal1
        folder: /Edge/vm/tkg
        network: /Edge/network/pg-edge-mgmt-145
        resourcePool: /Edge/host/EdgeCluster1/Resources/tkg_workload
        server: 10.90.144.10
        storagePolicyID: ""
        template: /Edge/vm/templates/photon-3-kube-v1.25.7+vmware.2
        tlsThumbprint: ""
    - name: user
      value:
        sshAuthorizedKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCw+bKF5H9+GIfmRd8OL4Lh+e07wYGiumwp4Qu2xSuqNWsDlF3Q6Mc6D5gtCDqlE1rIyeUJHoivQFO1WBd3q1fUvTA56i41K4QB8MycYG1Nz3i1nbRmo6+5VSvYebPtCXw9lu2e2tCsEJFo/fB1Y9p4J990UIq7oQINTSU/SnMTl8FKcUCarsMTLOkPRtsbQJPdf+sn8GHmnIcFj0F47UHLMFpJvvh6ZpyXOMGuwV+P4LSU8C7QsnRJXDdVMntoSY9MDWp4L48dYMBJseZ2JXi1y4l5HPkHUdSVAOg21G4FlhJTJt5tDx4pxovVHYJdr5dTYE1gk8VVU9tLwv7xElkkOziiAULEcm1gMETwGY/5QRpN461vW/2D5EpdYgd3ke0kT5xUdGyPFzK5vu7UKLX9L32ZBtSCfPhzkF38aP2XWtlgUh7dOEBkY/5T5XnqwfHW9EAIb1nif31PNW+hHH1OEL01D9IJHfWl8ygfYKriFxZmsTs0gzxcXepozuYTIopJMl75WrYOnva/vERBNVNOS9CcPFNXJc+TdLwMYaz6EXtFMaNRhy1m3Sdik0IwhBoiCVEHz+QhDHOxqgmYf3CCdNG/0dhaZDFVvsSYclYQzXIT4U7LMerHezzuPMqULHi+rAmuHU4WRubOIkWxJFiwpuHdtDtD+be89FA2LxP/FQ==
    - name: controlPlane
      value:
        machine:
          diskGiB: 20
          memoryMiB: 4096
          numCPUs: 4
    version: v1.25.7+vmware.1-tiny.2
