kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-data
spec:
  #storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        resources:
          limits:
            cpu: "2"
            memory: "3Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        ports:
        - containerPort: 9090
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        volumeMounts:
        - mountPath: /data
          name: data 
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-data

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      name: console
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: api
      port: 9000
      targetPort: 9000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 100
  type: LoadBalancer
