
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data 
          mountPath: /usr/share/nginx/html/data
        - name: indexpage
          mountPath: /usr/share/nginx/html
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nginx-data
      - name: indexpage
        configMap:
          name: nginx-page
--- 


