kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.test2.home.tanzu.rocks,test2.home.tanzu.rocks'
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
