apiVersion: v1
kind: Pod
metadata:
  name: trustworthy-pod
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default 
spec: 
  containers:
    - name: trustworthy-container
      image: pks-harbor.syddsc.local/library/nginx:latest
