apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongo-t1-1
  namespace: tenant1
spec:
  version: "4.1.7"
  storageType: Durable
  storage:
    storageClassName: ”wcp-storage-general"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate