apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-lychee
  namespace: default
spec:
  version: "8.0-v2"
  storageType: Durable
  storage:
    storageClassName: "wcp-storage-general"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
