apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-master1
  namespace: elk
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "128M"
#            cpu: "0.1"
          limits:
            memory: "256M"
#            cpu: "0.2"
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.6.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512M"
            cpu: "0.2"
          limits:
            memory: "1G"
            cpu: "0.5"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
        - mountPath: /elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          name: elasticconfig
      volumes:
          - name: storage
            persistentVolumeClaim:
              claimName: es-master1 
          - name: elasticconfig
            configMap:
              name: elasticsearch-config
              items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
